<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260619132702 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trajet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude_depart DOUBLE PRECISION NOT NULL, latitude_arrivee DOUBLE PRECISION NOT NULL, longitude_depart DOUBLE PRECISION NOT NULL, longitude_arrivee DOUBLE PRECISION NOT NULL, adresse_depart VARCHAR(100) NOT NULL, adresse_arrivee VARCHAR(100) NOT NULL, distance DOUBLE PRECISION NOT NULL, duree INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE covoiturage ALTER statut TYPE VARCHAR(255)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE trajet');
        $this->addSql('ALTER TABLE covoiturage ALTER statut TYPE VARCHAR(50)');
    }
}
