<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618073448 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, commentaire TEXT NOT NULL, note INT NOT NULL, statut_avis VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE covoiturage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, adresse_depart VARCHAR(100) NOT NULL, adresse_arrivee VARCHAR(100) NOT NULL, date_depart TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_arrivee TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prix DOUBLE PRECISION NOT NULL, place_disponible INT NOT NULL, voyage_ecologique BOOLEAN NOT NULL, statut VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE entreprise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, adresse VARCHAR(100) NOT NULL, presentation TEXT NOT NULL, email VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(50) DEFAULT NULL, pseudo VARCHAR(50) NOT NULL, prenom VARCHAR(50) DEFAULT NULL, date_naissance DATE DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, credits INT DEFAULT NULL, telephone INT DEFAULT NULL, is_conducteur BOOLEAN NOT NULL, is_passager BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE vehicule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_immatriculation VARCHAR(50) NOT NULL, date_immatriculation DATE NOT NULL, modele VARCHAR(50) NOT NULL, couleur VARCHAR(50) NOT NULL, marque VARCHAR(50) NOT NULL, energie VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE covoiturage');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vehicule');
    }
}
